// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// gtf2SAF
List gtf2SAF(std::string fileName);
RcppExport SEXP _TranslaSeq_gtf2SAF(SEXP fileNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fileName(fileNameSEXP);
    rcpp_result_gen = Rcpp::wrap(gtf2SAF(fileName));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TranslaSeq_gtf2SAF", (DL_FUNC) &_TranslaSeq_gtf2SAF, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_TranslaSeq(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
